rules:
  - origin: Spam? # IMAP origin folder
    destination: INBOX # IMAP destination folder
    threshold: 5.0 # Threshold to be considered Spam
    move_not_spam: true  # If true, move only the emails classified as not Spam. if false move only Spam emails

uid_files_path: ./ # Were to store UID files with last UID processed. Always add trailing dash!
llm:
  provider: ollama # Currently only supported: {ollama, openai, bedrock}
  model_id: gemma3:1b

interval: 60 # Time between IMAP searches for new emails
concurrency: false # True if emails will processed concurrently by the LLM (might cause problems with ollama)
whitelisted_domains: # Domains that will be ignored (not processed by the program)
  - gmail.com
  - hotmail.com


